# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-20 02:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescripcionFormulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_presentacion', models.DateField()),
                ('mes_reportado', models.CharField(choices=[('ENERO', 'ENERO'), ('FEBRERO', 'FEBRERO'), ('MARZO', 'MARZO'), ('ABRIL', 'ABRIL'), ('MAYO', 'MAYO'), ('JUNIO', 'JUNIO'), ('JULIO', 'JULIO'), ('AGOSTO', 'AGOSTO'), ('SEPTIEMBRE', 'SEPTIEMBRE'), ('OCTUBRE', 'OCTUBRE'), ('NOVIEMBRE', 'NOVIEMBRE'), ('DICIEMBRE', 'DICIEMBRE')], max_length=20)),
                ('nombre_proyecto', models.CharField(max_length=20)),
                ('nombre_operador', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=20)),
                ('num_contrato', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('persona_diligencia', models.CharField(max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('correo', models.CharField(max_length=50, null=True)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Edades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_edad', models.IntegerField(default=0)),
                ('de_0_a_6', models.IntegerField(default=0)),
                ('de_7_a_11', models.IntegerField(default=0)),
                ('de_12_a_14', models.IntegerField(default=0)),
                ('de_15_a_17', models.IntegerField(default=0)),
                ('de_18_a_25', models.IntegerField(default=0)),
                ('de_26_a_60', models.IntegerField(default=0)),
                ('mas_de_60', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MunicipioAfectado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('poblacion', models.CharField(choices=[('RURAL', 'RURAL'), ('URBANO', 'URBANO')], max_length=20)),
                ('descripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.DescripcionFormulario')),
                ('municipio_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Municipios')),
            ],
        ),
        migrations.CreateModel(
            name='PersonasConDiscapacidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_fisica_m', models.IntegerField(default=0)),
                ('cant_fisica_f', models.IntegerField(default=0)),
                ('cant_sensorial_m', models.IntegerField(default=0)),
                ('cant_sensorial_f', models.IntegerField(default=0)),
                ('cant_intelectual_m', models.IntegerField(default=0)),
                ('cant_intelectual_f', models.IntegerField(default=0)),
                ('total_m', models.IntegerField(default=0)),
                ('total_f', models.IntegerField(default=0)),
                ('total_poblacion', models.IntegerField(default=0)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.MunicipioAfectado')),
            ],
        ),
        migrations.CreateModel(
            name='PersonasSinDiscapacidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_indigenas_m', models.IntegerField(default=0)),
                ('cant_indigenas_f', models.IntegerField(default=0)),
                ('cant_afro_m', models.IntegerField(default=0)),
                ('cant_afro_f', models.IntegerField(default=0)),
                ('cant_raizal_m', models.IntegerField(default=0)),
                ('cant_raizal_f', models.IntegerField(default=0)),
                ('cant_palenque_m', models.IntegerField(default=0)),
                ('cant_palenque_f', models.IntegerField(default=0)),
                ('cant_campesino_m', models.IntegerField(default=0)),
                ('cant_campesino_f', models.IntegerField(default=0)),
                ('cant_romm_m', models.IntegerField(default=0)),
                ('cant_romm_f', models.IntegerField(default=0)),
                ('cant_lgbti', models.IntegerField(default=0)),
                ('cant_singrupo_m', models.IntegerField(default=0)),
                ('cant_singrupo_f', models.IntegerField(default=0)),
                ('total_m', models.IntegerField(default=0)),
                ('total_f', models.IntegerField(default=0)),
                ('total_poblacion', models.IntegerField(default=0)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.MunicipioAfectado')),
            ],
        ),
        migrations.AddField(
            model_name='edades',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.MunicipioAfectado'),
        ),
    ]
