# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-20 02:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formularios', '0001_initial'),
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='descripcionformulario',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='descripcionformulario',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Departamentos'),
        ),
        migrations.AddField(
            model_name='descripcionformulario',
            name='municipio_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Municipios'),
        ),
    ]
