# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-20 02:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id_departamento', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Departamentos',
                'db_table': 'departamentos',
                'managed': True,
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id_municipio', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('municipio', models.CharField(max_length=50)),
                ('flag', models.IntegerField(blank=True, null=True)),
                ('id_departamento', models.ForeignKey(db_column='id_departamento', on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Departamentos')),
            ],
            options={
                'verbose_name': 'Municipios',
                'db_table': 'municipios',
                'managed': True,
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id_pais', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'Pais',
                'db_table': 'paises',
                'managed': True,
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.AddField(
            model_name='departamentos',
            name='id_pais',
            field=models.ForeignKey(db_column='id_pais', on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Paises'),
        ),
    ]
